apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: deployments-retail-spill-policy
spec:

  # this section prioritizes workload clusters in the order listed below
  orderedClusterSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: [selvi-onprem, selvi-cloud]

  # this policy matches those resources that have this label' key value pair
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        retail-store-sample: dep-spill

  # this policy matches all resources that have the key listed below 
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: Exists

  # K8s resources will be grouped by this label key i.e. those with the same "value" for this key will be 
  # placed together in a single k8s workload cluster 
  groupBy:
    labelKey: retail-store-group
