apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: prom-policy
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In 
        values:
          - monitoring
  clusterSelector:
    matchLabels:
      kubernetes.io/metadata.name: selvi-onprem
  resourceSelectors:
    labelSelectors:
      - matchLabels:
          app.kubernetes.io/instance: "prom"
  # groupBy:
  #   labelKey: app.kubernetes.io/name
