apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: prom-grafana-ns-policy
spec:
  spreadConstraints:
    spreadMode: Duplicate
    topologyKey: kubernetes.io/metadata.name
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        app: promsetup
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: Exists
  groupBy:
    labelKey: app
